name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: ^4.6.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  logger: ^1.1.0
  intl: ^0.17.0
  country_picker: ^2.0.19
  shared_preferences: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/
    # - assets/page-1/images/vector-Dxm.png
    # - assets/page-1/images/vector-xiu.png
    # - assets/page-1/images/vector-yjf.png
    # - assets/page-1/images/vector-BJh.png
    # - assets/page-1/images/vector-Lwb.png
    # - assets/page-1/images/vector-6Ly.png
    # - assets/page-1/images/vector-gpH.png
    # - assets/page-1/images/vector-6k1.png
    # - assets/page-1/images/vector-sk5.png
    # - assets/page-1/images/vector-8V7.png
    # - assets/page-1/images/vector-KMs.png
    # - assets/page-1/images/vector-pch.png
    # - assets/page-1/images/vector-4ss.png
    # - assets/page-1/images/vector-cuo.png
    # - assets/page-1/images/vector-ka5.png
    # - assets/page-1/images/vector-2Sd.png
    # - assets/page-1/images/vector-voj.png
    # - assets/page-1/images/vector-Dub.png
    # - assets/page-1/images/vector-QMw.png
    # - assets/page-1/images/vector-fE1.png
    # - assets/page-1/images/vector-85o.png
    # - assets/page-1/images/vector-cEM.png
    # - assets/page-1/images/vector-YXB.png
    # - assets/page-1/images/vector-MJq.png
    # - assets/page-1/images/vector-8L9.png
    # - assets/page-1/images/vector-9iy.png
    # - assets/page-1/images/vector-PW9.png
    # - assets/page-1/images/vector-wQV.png
    # - assets/page-1/images/vector-rMf.png
    # - assets/page-1/images/vector-Xd3.png
    # - assets/page-1/images/vector-jRs.png
    # - assets/page-1/images/vector-Qws.png
    # - assets/page-1/images/vector-kYy.png
    # - assets/page-1/images/vector-kEV.png
    # - assets/page-1/images/vector-hK7.png
    # - assets/page-1/images/vector-65w.png
    # - assets/page-1/images/vector-YHw.png
    # - assets/page-1/images/vector-5Ah.png
    # - assets/page-1/images/vector-f61.png
    # - assets/page-1/images/vector-T7F.png
    # - assets/page-1/images/vector-Pww.png
    # - assets/page-1/images/vector-acq.png
    # - assets/page-1/images/vector-74M.png
    # - assets/page-1/images/vector-3V3.png
    # - assets/page-1/images/vector-xM7.png
    # - assets/page-1/images/vector-Vbw.png
    # - assets/page-1/images/vector-dTF.png
    # - assets/page-1/images/vector-B9B.png
    # - assets/page-1/images/vector-Ue5.png
    # - assets/page-1/images/vector-ZAq.png
    # - assets/page-1/images/vector-fjf.png
    # - assets/page-1/images/vector-CDo.png
    # - assets/page-1/images/vector-FbP.png
    # - assets/page-1/images/vector-U2D.png
    # - assets/page-1/images/vector-cPK.png
    # - assets/page-1/images/vector-HVT.png
    # - assets/page-1/images/vector-z8y.png
    # - assets/page-1/images/vector-SWm.png
    # - assets/page-1/images/vector-cTB.png
    # - assets/page-1/images/vector-xfT.png
    # - assets/page-1/images/vector-Uth.png
    # - assets/page-1/images/vector-WaV.png
    # - assets/page-1/images/vector-Pzy.png
    # - assets/page-1/images/vector-22M.png
    # - assets/page-1/images/vector-nQq.png
    # - assets/page-1/images/vector-7CD.png
    # - assets/page-1/images/vector-qP7.png
    # - assets/page-1/images/vector-mXf.png
    # - assets/page-1/images/vector-6K3.png
    # - assets/page-1/images/vector-1wo.png
    # - assets/page-1/images/vector-nQ9.png
    # - assets/page-1/images/vector-NQH.png
    # - assets/page-1/images/vector-gvm.png
    # - assets/page-1/images/vector-6jT.png
    # - assets/page-1/images/vector-N25.png
    # - assets/page-1/images/vector-tMf.png
    # - assets/page-1/images/vector-rrD.png
    # - assets/page-1/images/vector-kty.png
    # - assets/page-1/images/vector-D1s.png
    # - assets/page-1/images/vector-nj3.png
    # - assets/page-1/images/vector-GjK.png
    # - assets/page-1/images/vector-JRX.png
    # - assets/page-1/images/vector-zp1.png
    # - assets/page-1/images/vector-rRX.png
    # - assets/page-1/images/vector-kmo.png
    # - assets/page-1/images/vector-cgh.png
    # - assets/page-1/images/vector-vSV.png
    # - assets/page-1/images/vector-FUm.png
    # - assets/page-1/images/vector-1eH.png
    # - assets/page-1/images/vector-gpq.png
    # - assets/page-1/images/vector-Gho.png
    # - assets/page-1/images/vector-aiV.png
    # - assets/page-1/images/vector-X7w.png
    # - assets/page-1/images/vector-oLu.png
    # - assets/page-1/images/vector-t2u.png
    # - assets/page-1/images/vector-w9b.png
    # - assets/page-1/images/vector-uzy.png
    # - assets/page-1/images/vector-WYq.png
    # - assets/page-1/images/vector-e7s.png
    # - assets/page-1/images/vector-kRo.png
    # - assets/page-1/images/vector-uT7.png
    # - assets/page-1/images/vector-dP7.png
    # - assets/page-1/images/vector-NLh.png
    # - assets/page-1/images/vector-EGR.png
    # - assets/page-1/images/vector-f1b.png
    # - assets/page-1/images/vector-YFj.png
    # - assets/page-1/images/vector-Sru.png
    # - assets/page-1/images/vector-KBw.png
    # - assets/page-1/images/vector-FyK.png
    # - assets/page-1/images/vector-FQu.png
    # - assets/page-1/images/vector-d77.png
    # - assets/page-1/images/vector-Aru.png
    # - assets/page-1/images/vector-iWM.png
    # - assets/page-1/images/vector-no3.png
    # - assets/page-1/images/vector-e5o.png
    # - assets/page-1/images/vector-5yj.png
    # - assets/page-1/images/vector-Kf7.png
    # - assets/page-1/images/vector-53w.png
    # - assets/page-1/images/vector-AND.png
    # - assets/page-1/images/vector-HUm.png
    # - assets/page-1/images/vector-A6d.png
    # - assets/page-1/images/vector-2ed.png
    # - assets/page-1/images/vector-9z9.png
    # - assets/page-1/images/vector-AwB.png
    # - assets/page-1/images/vector-ErV.png
    # - assets/page-1/images/vector-R1B.png
    # - assets/page-1/images/vector-9hs.png
    # - assets/page-1/images/vector-RBX.png
    # - assets/page-1/images/vector-Brq.png
    # - assets/page-1/images/vector-ros.png
    # - assets/page-1/images/vector-83B.png
    # - assets/page-1/images/vector-7bo.png
    # - assets/page-1/images/vector-HwX.png
    # - assets/page-1/images/vector-bCV.png
    # - assets/page-1/images/vector-Jo3.png
    # - assets/page-1/images/vector-Xvh.png
    # - assets/page-1/images/vector-NJM.png
    # - assets/page-1/images/vector-8im.png
    # - assets/page-1/images/vector-KUM.png
    # - assets/page-1/images/vector-nFK.png
    # - assets/page-1/images/vector-Ufs.png
    # - assets/page-1/images/vector-ujX.png
    # - assets/page-1/images/vector-5Mj.png
    # - assets/page-1/images/vector-NJD.png
    # - assets/page-1/images/vector-mFf.png
    # - assets/page-1/images/vector-Xry.png
    # - assets/page-1/images/vector-kRX.png
    # - assets/page-1/images/vector-FYd.png
    # - assets/page-1/images/vector-WCH.png
    # - assets/page-1/images/vector-quK.png
    # - assets/page-1/images/vector-JTT.png
    # - assets/page-1/images/vector-KNR.png
    # - assets/page-1/images/vector-RCV.png
    # - assets/page-1/images/vector-XRs.png
    # - assets/page-1/images/vector-Gau.png
    # - assets/page-1/images/ellipse-1.png
    # - assets/page-1/images/vector-zvm.png
    # - assets/page-1/images/vector-z2D.png
    # - assets/page-1/images/vector-Tds.png
    # - assets/page-1/images/vector-S5o.png
    # - assets/page-1/images/vector-1.png
    # - assets/page-1/images/vector-Ux9.png
    # - assets/page-1/images/vector-aBb.png
    # - assets/page-1/images/ellipse-2.png
    # - assets/page-1/images/vector-YLR.png
    # - assets/page-1/images/log-out-svgrepo-com-1.png
    # - assets/page-1/images/ellipse-1-aJ5.png
    # - assets/page-1/images/vector-YSV.png
    # - assets/page-1/images/vector-HVB.png
    # - assets/page-1/images/vector-NMX.png
    # - assets/page-1/images/vector-iJm.png
    # - assets/page-1/images/vector-kt9.png
    # - assets/page-1/images/ellipse-2-uFX.png
    # - assets/page-1/images/vector-v7K.png
    # - assets/page-1/images/data-svgrepo-com-1.png
    # - assets/page-1/images/data-svgrepo-com-1-txR.png
    # - assets/page-1/images/vector-84h.png
    # - assets/page-1/images/polygon-1.png
    # - assets/page-1/images/talking-by-phone-svgrepo-com-1.png
    # - assets/page-1/images/talking-by-phone-svgrepo-com-1-qF7.png
    # - assets/page-1/images/vector-JUh.png
    # - assets/page-1/images/deposit-svgrepo-com-1.png
    # - assets/page-1/images/log-out-svgrepo-com-1-mb7.png
    # - assets/page-1/images/vector-unR.png
    # - assets/page-1/images/home-svgrepo-com-1.png
    # - assets/page-1/images/deposit-svgrepo-com-1-PHK.png
    # - assets/page-1/images/faq-svgrepo-com-1.png
    # - assets/page-1/images/data-svgrepo-com-1-4w3.png
    # - assets/page-1/images/deposit-svgrepo-com-1-hvZ.png
    # - assets/page-1/images/home-svgrepo-com-1-jQd.png
    # - assets/page-1/images/data-svgrepo-com-1-8uF.png
    # - assets/page-1/images/polygon-1-gAd.png
    # - assets/page-1/images/talking-by-phone-svgrepo-com-1-9f7.png
    # - assets/page-1/images/log-out-svgrepo-com-1-1q3.png
    # - assets/page-1/images/log-out-svgrepo-com-1-M4u.png
    # - assets/page-1/images/polygon-1-XXf.png
    # - assets/page-1/images/home-svgrepo-com-1-fMb.png
    # - assets/page-1/images/log-out-svgrepo-com-1-Zz1.png
    # - assets/page-1/images/vector-EZf.png
    # - assets/page-1/images/vector-7dT.png
    # - assets/page-1/images/polygon-1-dLu.png
    # - assets/page-1/images/log-out-svgrepo-com-1-WVf.png
    # - assets/page-1/images/polygon-1-ESu.png
    # - assets/page-1/images/talking-by-phone-svgrepo-com-1-v81.png
    # - assets/page-1/images/deposit-svgrepo-com-1-vHf.png
    # - assets/page-1/images/data-svgrepo-com-1-xaM.png
    # - assets/page-1/images/home-svgrepo-com-1-sJZ.png
    # - assets/page-1/images/vector-yQm.png
    # - assets/page-1/images/vector-BXP.png
    # - assets/page-1/images/vector-7fF.png
    # - assets/page-1/images/vector-k3K.png
    # - assets/page-1/images/vector-bhT.png
    # - assets/page-1/images/vector-igq.png
    # - assets/page-1/images/vector-muK.png
    # - assets/page-1/images/vector-FtM.png
    # - assets/page-1/images/vector-uYu.png
    # - assets/page-1/images/deposit-svgrepo-com-1-WWd.png
    # - assets/page-1/images/vector-M4V.png
    # - assets/page-1/images/data-svgrepo-com-1-NJu.png
    # - assets/page-1/images/talking-by-phone-svgrepo-com-1-jB7.png
    # - assets/page-1/images/vector-1-gt1.png
    # - assets/page-1/images/deposit-svgrepo-com-1-i2d.png
    # - assets/page-1/images/home-svgrepo-com-1-qTP.png
    # - assets/page-1/images/home-svgrepo-com-1-h1j.png
    # - assets/page-1/images/talking-by-phone-svgrepo-com-1-kEu.png
    # - assets/page-1/images/polygon-1-TQD.png
    # - assets/page-1/images/home-svgrepo-com-1-ApR.png
    # - assets/page-1/images/deposit-svgrepo-com-1-ram.png
    # - assets/page-1/images/vector-DNq.png
    # - assets/page-1/images/vector-yuj.png
    # - assets/page-1/images/talking-by-phone-svgrepo-com-1-YaV.png
    # - assets/page-1/images/ellipse-3-bg.png
    # - assets/page-1/images/log-out-svgrepo-com-1-MYm.png
    # - assets/page-1/images/data-svgrepo-com-1-ad7.png
    # - assets/page-1/images/vector-xfb.png
    # - assets/page-1/images/ellipse-3-bg-Try.png
    # - assets/page-1/images/polygon-1-22d.png
    # - assets/page-1/images/ellipse-3-bg-ums.png
    # - assets/page-1/images/ellipse-5-bg.png
    # - assets/page-1/images/ellipse-3-bg-bkD.png
    # - assets/page-1/images/ellipse-3-bg-xch.png
    # - assets/page-1/images/ellipse-3-bg-FWZ.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
